namespace FlashLive.Models.Contracts.Enums
{
    public enum SportType
    {
        ALPINE_SKIING = 39,
        AMERICAN_FOOTBALL = 5,
        AUSSIE_RULES = 18,
        AUTORACING = 32,
        BADMINTON = 21,
        BANDY = 10,
        BASEBALL = 6,
        BASKETBALL = 3,
        BEACH_SOCCER = 26,
        BEACH_VOLLEYBALL = 17,
        BIATHLON = 41,
        BOXING = 16,
        CRICKET = 13,
        CROSS_COUNTRY = 40,
        CYCLING = 34,
        DARTS = 14,
        ESPORTS = 36,
        FIELD_HOCKEY = 24,
        FLOORBALL = 9,
        FUTSAL = 11,
        GOLF = 23,
        HANDBALL = 7,
        HOCKEY = 4,
        HORSE_RACING = 35,
        KABADDI = 42,
        MMA = 28,
        MOTORACING = 33,
        MOTORSPORT = 31,
        NETBALL = 29,
        PESAPALLO = 30,
        RUGBY_LEAGUE = 19,
        RUGBY_UNION = 8,
        SKI_JUMPING = 38,
        SNOOKER = 15,
        SOCCER = 1,
        TABLE_TENNIS = 25,
        TENNIS = 2,
        VOLLEYBALL = 12,
        WATER_POLO = 22,
        WINTER_SPORTS = 37,
    }
}
